- name: Installing Nginx Server
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy roboshop configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: true

- name: Load NodeJS
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Load Prometheus Node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

