- name: Configure Erlang repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/{{ item }} | bash
  loop:
    - erlang/script.rpm.sh
    - rabbitmq-server/script.rpm.sh

- name: INstall RabbitMQ Server
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present


