- name: Copy LogStash Config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

