- name: Load NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Load Prometheus Node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter



