- name: Load NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Load Schema Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo_schema_setup

