- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download and extract app content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes

- name: Download and extract app content from nexus
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', 'roboshop.nexus.username', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', 'roboshop.nexus.password', region='us-east-1') }}@172.31.95.9:8081/repository/{{component}}/{{component}}-{{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.{{component}}.app_version', region='us-east-1') }}.zip
    dest: /app
    remote_src: yes


