- name: Configuring NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app_presetup.yml

# this step goes with CI
#- name: Load NodeJS Dependencies
#  ansible.builtin.shell: npm install
#  args:
#    chdir: /app

- name: Download DocumentDB Pem file
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem

- name: Load Schema
  ansible.builtin.import_tasks:
    file: mongo_schema_setup.yml
  when: load_schema

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml




