- name: Copy SystemnD File
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest:  /etc/systemd/system/{{ component }}.service

- name: Start {{ component }} Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes
